### ISSUE TITLE
"Patch ID "copy-raw-message" tried to patch a module, but it was undefined"

### ISSUE THREAD

**Issue by wouu** [vizality-community/copy-raw-message#1]
- plugin revision: 4484076
- vizality revision: [`3f4dc36`](https://github.com/vizality/vizality/commit/3f4dc36cb76a3b6f1229b94839e061c5eceb9c75)
- discord version and build number: stable 1.0.9003 111140
- os: windows 11

```
Patch ID "copy-raw-message" tried to patch a module, but it was undefined!
    at patch (C:\Users\****\vizality\src\core\modules\patcher\index.js:88:13)
    at CopyRawMessage.patchContextMenu (C:\Users\****\vizality\addons\plugins\copy-raw-message\index.js:20:20)
    at CopyRawMessage.start (C:\Users\****\vizality\addons\plugins\copy-raw-message\index.js:10:10)
    at C:\Users\****\vizality\src\core\entities\Plugin.js:285:26
    at new Promise (<anonymous>)
    at startPlugin (C:\Users\****\vizality\src\core\entities\Plugin.js:284:18)
    at CopyRawMessage._load (C:\Users\****\vizality\src\core\entities\Plugin.js:288:9)
    at C:\Users\****\vizality\src\core\managers\Addon.js:1:861
    at C:\Users\****\vizality\src\core\managers\Addon.js:364:145
    at _optionalChain (C:\Users\****\vizality\src\core\managers\Addon.js:1:839)
```

**Comment by wouu** [comment]
interestingly enough it seems to work if it is enabled after discord startup, but if it is enabled before discord starts up then it refuses to load
